image: afmartin3z/lighthouse:latest

variables:
  URL: https://0cf407e28655.ngrok.io
  LHCI_TOKEN: 587acafb-8a01-4aa1-9e0c-d902c661b10a
  URL:

stages:
  - report

review_report:
  stage: report
  image: afmartin3z/lighthouse:latest
  script:
    - echo $URL
    - lhci autorun --upload.target="lhci" --upload.token="$LHCI_TOKEN" --upload.serverBaseUrl="URL" --collect.url="$URL" --collect.settings.chromeFlags="--no-sandbox --headless --ignore-certificate-errors" --assert.preset="lighthouse:recommended" || exit 1
  allow_failure: true
  rules:
    - if: "$CI_COMMIT_REF_NAME !~ /master/"

static_review_report:
  stage: report
  image: afmartin3z/lighthouse:latest
  script:
    - npm install
    - npm run build
    - lhci autorun --upload.target=temporary-public-storage --collect.settings.chromeFlags="--no-sandbox" --assert.preset="lighthouse:recommended" || echo "LHCI failed!" && exit 1
  allow_failure: true
